### ISSUE TITLE
Error when running the example(folder test)

### ISSUE THREAD

**Issue by GrozaRobotov** [alduxvm/pyMultiWii#40]
Error:

Traceback (most recent call last):
  File "C:\Pyton.PROJECTS\pythonProject1\MyFile.py", line 18, in <module>
    board = MultiWii("/dev/ttyUSB0")
  File "C:\Pyton.PROJECTS\pythonProject1\venv\lib\site-packages\pymultiwii\__init__.py", line 79, in __init__
    self.ser = serial.Serial()
AttributeError: module 'serial' has no attribute 'Serial'

What am I doing wrong?

**Comment by Niko-La** [comment]
@GrozaRobotovFPV
`pip install pyserial`
